In [230]:
import pandas as pd
from math import floor
import glob, os
from tqdm.notebook import tqdm
import json
import plotly.express as px
import plotly.graph_objects as go
import geopandas as gpd
import numpy as np
import chart_studio
import chart_studio.plotly as py
import plotly.io as pio
import sys
sys.path.append("../lib/")
from dhondt import dhondt

pd.set_option('display.max_columns', None)

In [169]:
ELECCIONES_PROVINCIA_FILES_PATH = "../../data/raw/resultados_electorales/congreso_por_provincia/PROV_02_201911_1.xlsx"
ELECCIONES_MUNICIPIO_PATH = "../../data/staging/elecciones_generales_completas.csv"
ESCANIOS_PATH = "../../data/raw/escaños/escaños_2019.xlsx"
#GEOJSON_PATH = "../../data/raw/mapa_municipios/Municipios_IGN-shp/madrid_municipios_reduced.geojson"

username = 'politicai' # your username
api_key = 'REDACTED' # your api key - go to profile > settings > regenerate key
chart_studio.tools.set_credentials_file(username=username, api_key=api_key)
# py.plot(fig_object, filename = 'gdp_per_cap', auto_open=True)
# pio.write_html(fig, file=’index.html’, auto_open=True)

In [180]:
coalicion_a_favor = ["psoe", "podemos_iu", "eaj_pnv", "mas_pais_equo", "bng" ,
                     "teruel_existe!", "ecp_guanyem_el_canvi", "podemos_eu", "mes_compromis", "mas_pais", "m_pais_cha_equo"]
coalicion_en_contra = ["pp", "vox", "cs", "jxcat_junts", "cup_pr", "upn", "cca_pnc_nc", "Foro Asturias","prc", "na+"]
coalicion_abstencion = ["erc_sobiranistes", "eh_bildu"]

In [236]:
def clean_column_names(df):
    df.columns = df.columns.str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace(':', '').str.replace('(', '')
    df.columns = df.columns.str.replace('.', '').str.replace(')', '').str.replace('-', '_').str.replace(')', '')
    df.columns = df.columns.str.replace("á", "a").str.replace("é", "e").str.replace("í", "i").str.replace("ó", "o").str.replace("ú", "u")
    return df

def limpiar_elecciones_municipio(df):
    key_municipio_columns = ['nombre_de_comunidad', 'codigo_de_provincia', 'nombre_de_provincia',
               'codigo_de_municipio', 'nombre_de_municipio', 'poblacion',
               'numero_de_mesas', 'total_censo_electoral', 'total_votantes',
               'votos_validos', 'votos_a_candidaturas','votos_en_blanco','votos_nulos',
               'year', 'month', 'yearmonth', 'CODIGOINE']
    party_columns_municipio = [x for x in df.columns if x not in key_municipio_columns]
    df[party_columns_municipio] = df[party_columns_municipio].apply(pd.to_numeric)
    return df, party_columns_municipio


def limpiar_elecciones_provincia(df):
    diputados_cols = [x for x in df.columns if "Diputados" in x]
    df = df.drop(columns=diputados_cols)

    for idx, elem in enumerate(df.columns.values):
        if "Unnamed" in elem[0]:
            df.columns.values[idx]=("",df.columns.values[idx][1])
    df.columns = [' '.join(col).strip() for col in df.columns.values]
    df = clean_column_names(df)
    df.columns = [col.replace("_votos", "") for col in df.columns]

    numeric_columns = [x for x in df.columns if x not in ["nombre_de_comunidad", "codigo_de_provincia", "nombre_de_provincia"]]
    df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric)
    key_prov_columns = ["nombre_de_comunidad","codigo_de_provincia","nombre_de_provincia",
               "poblacion","numero_de_mesas","censo_electoral_sin_cera","censo_cera",
               "total_censo_electoral","solicitudes_voto_cera_aceptadas","total_votantes_cer",
               "total_votantes_cera","total_votantes","votos_validos","votos_a_candidaturas",
               "votos_en_blanco","votos_nulos"]
    party_columns_prov = [x for x in df.columns if x not in key_prov_columns]
    
    return df, party_columns_prov

def calculate_dhondt(df_row_votes, party_columns, n_seats, min_per=0.03):
    # matriz base
    parties_T = df_row_votes[party_columns].T
    total_votos = int(parties_T.sum())
    parties_T = parties_T[parties_T[parties_T.columns[0]] > 0.03*total_votos]
    parties_T = parties_T.sort_values(by = parties_T.columns[0], ascending=False) 
    parties_T = parties_T.rename(columns={parties_T.columns[0]:"votos"})
    #escaños acumulados
    current_votes = parties_T.copy()
    current_votes["acumulado"] = 1
    current_votes = current_votes.drop(columns =["votos"])
    #calculo
    for idx in range(1,n_seats+1):
        parties_T[f'escaño_{idx}'] = (parties_T["votos"] / current_votes["acumulado"]).astype(int)
        max_col = parties_T[f'escaño_{idx}'].idxmax()
        #print(f"escaño {idx}: ", max_col)
        current_votes.loc[current_votes.index == max_col,"acumulado"] += 1 
    current_votes["acumulado"] = current_votes["acumulado"] -1
    
    return parties_T.T, current_votes

## Datos electorales municipio

In [237]:
df_municipio = pd.read_csv(ELECCIONES_MUNICIPIO_PATH, sep="|", dtype={"CODIGOINE":str}, index_col=False)
df_municipio, party_columns_municipio = limpiar_elecciones_municipio(df_municipio)
print(df_municipio.shape)
df_municipio.head(2)

(121361, 646)

,Unnamed: 0,nombre_de_comunidad,codigo_de_provincia,nombre_de_provincia,codigo_de_municipio,nombre_de_municipio,poblacion,numero_de_mesas,total_censo_electoral,total_votantes,votos_validos,votos_a_candidaturas,votos_en_blanco,votos_nulos,pp,psoe,iu,ciu,eaj_pnv,cc,bng,hb,erc,pa,ea,uv,lve,cha,uc,upv_bn,psm_ene,cdn,lv_gv,prt,pcpe,ph,pas,upl,fea,icv_gorordo,lv,cex,um,tc_pnc,priojano,pec,urcl,na,aun,cr,sos,prepal,frepic,pspc,prcm,fpg,siex,prv,prim,fei,nr,picc,ar,env,pae,pb,pcn,upra,uad,adec,vdpa,n,alas,aba,prgu,lae,dsa,lg,piz,pnm,por,afit,ccv,year,month,yearmonth,ciudadanos,podemos_iu_equo,vox,erc_sobiranistes,ecp_guanyem_el_canvi,jxcat_junts,eh_bildu,podemos_eu_mareas_en_comun_equo,cca_pnc,na+,compromis_2019,prc,pacma,front_republica,recortes_cero_gv,nca,pact,ara_mes_esquerra,gbai,pum+j,en_marea,pcte,el_pi,axsi,pcoe,avant_adelante_los_verdes,eb,cpm,somos_region,pcpa,uig_som_cuides,erpv,izqp,pcpc,ahora_canarias,cxg,ppso,cnv,cex_crex_prex,pr+,p_lib,cilu_linares,andecha_astur,"""jf""",pyln,fia,fe_de_las_jons,f8,solidaria,dpl,union_regionalista,centrados,vou,dp,pdsje_udec,izar,risa,c_21,+mas+,udt,ap_pdp,ucd,pce,cds,fn,pst,ee,psa_pa,pcc,b_psg,upc,ne,se,uce,pce_m_l,eu,eg,ac_cc,upv,cuc,ps,mfe,eupv,aeba,psm,lc_cosi,psa,env_urv,aegi,ce_fcc,fe_jons,fic,pnc,padl,cc1,idg,fe_i,lcr_mc,lcr,aci,pre,pnc1,pdb,mcate,asdc,ir,fa,em,pcu,pc,emk,bia,cir,podemos,en_comu,iu_upec,podemos_com,erc_catsi,dl,podemos_en,upyd,nos,uniocat,recortes_ce,mes,ccd,fe_de_las_j,x_la_izquie,somval,sain,centro_mode,pt,canarias_de,arapv,eu_ex,dn,ifem,en_positiu,cilus,cra,ln,avant,mlgxsi,pfyv,aju,independien,fdee,soluciona,"js,pc",pld,oe,ruiz_mateos,lv_lv,pte_uc,par,aic,cg,psg_eg,av_mec,verde,acn,csd,png_pg,exu,pore,igc,ped,pam,grm,una,ua_cha,ub,ceu,arde,sev,mv,pancal,coa,pee_lv,r_x_c,tagoror,prb,pnem,ppr,lki_emk,pce_ml,cd,un,pnv,pte,psoe_h,ort,erfn,mc_oic,bnpg,c_upc,pg_pog_psg,bean,pcarl,pct,ufv,fjonsa,upn,oce_br,psar___psda,plib,urv,pnpv,unai,pdpcan,smim,psin,ule,e_catala,cic,p_cant,dscc,pprov,lc,ocebr_uce,cna,pippa,poc,cime,fe_uf,uf_fi_at,verdes,ea_eue,le,arm_ade,pap,upca,ua,gil,pgc,pln,e_u,ummp,pec_verde,nps,p_riojano,cng,ag,prex,sees,arcoiris,app,pvpa,mce,atf,aigranc,fpe,aa,fe_a,unida,udla,os,conceyu,piap,abe,pitrcg,if,p_tagoror,mces,us,ince,freixes,ccl,ap,psp_us,pdpc,fdc_edc,udc_idcc,ec_fed,fdi,asdci,aet,an18,rse,fut,caic,esb,pspv,indep,dcv,psg,fjons,afn,indep1,ura,lliga,uan,anepa_cp,fl,div,cja,cups,ccia,uab,uras,fni,ppcan,ms,asa,mfa,anv,indep2,indep3,indep4,dcar,udib,indep5,cup,pscan,faa,pim,indep6,prsv,icu,psde,indep7,indep8,pdg,indep9,indep10,indep11,aeicyu,cuir,cipye,pli,adc,bai,indep12,cai,ic_v,bloc_verds,psm_en,uc_cds,lv_cm,fe,posi,ev_av,pil,es2000,pade,um_inme,ia,blm,fei_fe_2000,pcl,autonomo,ec,pkd,el_papi,a,prex_crex,dg,upz,cnc,peda,li_lit_ci,paviel,ir_pre,usi,pnca,inar,up_can,ural,ccs,csd_l,pf,ppcr,upb,ii,unib,prib,tpc,cives,mash,pdep,an,eh,iu_lv,amaiur,esquerra,equo,cc_nc_pnc,compromis_q,fac,pxc,anticapitalistas,piratacat,espana_2000,rps,hartosorg,pirata,anc,cdl,pcas,uxv,prao,caballas,cxxi,unidad_del_pueblo,andecha,acima,ucit,dec,cyd,prde,internet,pre_r,basta_ya,pdyc,hd,sxt,dne,cc_pnc,ca,na_bai,nc_ccn,aralar,bloc_idpv_ev_ee,unitat_per_les_illes,psd,cenb,ev_ae,pdeal,rcn_nok,ev_lv,aes,e_2000,rc,cva,ei,tc,amd,pdlpea,partido_riojano,abla,extremadura_unida,pxcat,pnf_no_fumadores,uleg,onv,frente,cdes,plci,pleve,li_litci,plrv,centristas_pctr,pcua,ucpic,irv,mupc,puede,piib,pb_ub,ctc,ud_ca,imc,paie,td,cdas,ave,ucl,n_som,axb,ixc,icbur,agruci,phache,ap_pdp_pl,muc,prd,ac_inc,av,upr,pspa,cun,psdc,adei,cl,loc,cn,pmcn,prm,prov,ae_aic,paec,lki,podemos_iu,mas_pais_equo,cup_pr,podemos_eu,cca_pnc_nc,mes_compromis,teruel_existe!,mas_pais,m_pais_cha_equo,mes_esquerra,xav,contigo,pdsje,mas,unidos_si_acps_def,mdyc,aunacv,canda,ecp,podemos_compromis_eupv,cdc,podemos_en_marea_anova_eu,recortes_cero_grupo_verde,bng_nos,si,centro_moderado,ccd_ci,and,jxc,repo,independientes_fia,entaban,alcd,fme,hrts_ln,bloc_ev,"psm_en,eu,ev,er",aralar_zutik,lv_e,lvcm,pcannabis,lvrm,msr,ides,apca,gve,ci,adn,ptpre,upsa,pmar,otradem,asi,psicv,prf,axgc,a_iz,ias,ucm,zu,fde,psda,amaga,pnt,ccse,pdn,gphae,CODIGOINE
0,0,Andalucía,4,Almería,1,ABLA ...,1597,2,1273,1090,1088,1082,6,2,442.0,558,70.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996,3,199603,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,04001
1,1,Andalucía,4,Almería,2,ABRUCENA ...,1476,2,1183,1036,1028,1024,4,8,253.0,659,99.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996,3,199603,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,04002

## Datos electorales provincia noviembre 2019

In [238]:
df_provincia_nov_2019_raw = pd.read_excel(io=ELECCIONES_PROVINCIA_FILES_PATH, header=[0,1], skiprows=4)
df_provincia, party_columns_prov = limpiar_elecciones_provincia(df_provincia_nov_2019_raw)
print(df_provincia.shape)
df_provincia.head(2)

(54, 83)

,nombre_de_comunidad,codigo_de_provincia,nombre_de_provincia,poblacion,numero_de_mesas,censo_electoral_sin_cera,censo_cera,total_censo_electoral,solicitudes_voto_cera_aceptadas,total_votantes_cer,total_votantes_cera,total_votantes,votos_validos,votos_a_candidaturas,votos_en_blanco,votos_nulos,psoe,pp,vox,podemos_iu,erc_sobiranistes,cs,jxcat_junts,ecp_guanyem_el_canvi,eaj_pnv,eh_bildu,mas_pais_equo,cup_pr,podemos_eu,cca_pnc_nc,na+,mes_compromis,bng,prc,teruel_existe!,pacma,mas_pais,recortes_cero_gv,pum+j,m_pais_cha_equo,mes_esquerra,axsi,pcpe,pcte,gbai,upl,pcoe,cpm,eb,erpv,xav,avant_adelante_los_verdes,verdes,ph,ifem,uig_som_cuides,somos_region,izqp,ahora_canarias,contigo,cha,ppso,extremadura_unida,pdsje,p_lib,mas,unidos_si_acps_def,prepal,andecha,mdyc,pyln,fe_de_las_jons,aunacv,union_regionalista,canda,fia,solidaria,risa,centrados,dpl,izar,c_21,udt
0,Andalucía,4,Almería,709340.0,809.0,460639.0,41988.0,502627.0,2923.0,303481.0,1933.0,305414.0,302424.0,299763.0,2661.0,2990.0,89295.0,78072.0,80714.0,24400.0,0.0,22835.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2582.0,0.0,360.0,371.0,0.0,0.0,318.0,303.0,0.0,0.0,0.0,0.0,0.0,513.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Andalucía,11,Cádiz,1238714.0,1520.0,973238.0,29057.0,1002295.0,3485.0,621965.0,2230.0,624195.0,616079.0,606858.0,9221.0,8116.0,188271.0,111089.0,131205.0,93541.0,0.0,55490.0,0.0,0.0,0.0,0.0,11316.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8437.0,0.0,915.0,707.0,0.0,0.0,3509.0,639.0,0.0,0.0,0.0,1739.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Escaños

In [239]:
df_escanios = pd.read_excel(ESCANIOS_PATH)
df_escanios.head()

   codigo_de_provincia             nombre_de_provincia  escaños
0                   15  A Coruña                              8
1                    2  Albacete                              4
2                    3  Alicante / Alacant                   12
3                    4  Almería                               6
4                    1  Araba / Álava                         4

## Dhondt

In [240]:
prov_dict = {}
for index, row in df_escanios.iterrows():
    #print(row["nombre_de_provincia"])
    df_provincia_row = df_provincia[df_provincia.codigo_de_provincia == row["codigo_de_provincia"]]
    tabla_dhondt, escanios = calculate_dhondt(df_row_votes=df_provincia_row, 
                                              party_columns=party_columns_prov, n_seats=row["escaños"])

    prov_dict[str(row["codigo_de_provincia"])]={}
    prov_dict[str(row["codigo_de_provincia"])]["tabla"] = tabla_dhondt
    prov_dict[str(row["codigo_de_provincia"])]["escaños"] = escanios
    #print(tabla_dhondt.tail(2))

In [241]:
for cod_prov in df_escanios["codigo_de_provincia"].unique():
    print(df_escanios[df_escanios["codigo_de_provincia"] == ])
    last_line = prov_dict[str(cod_prov)]["tabla"].tail(1)
    gold = last_line.idxmax(axis=1).to_list()
    silver = last_line[[x for x in last_line.columns if x not in gold]].idxmax(axis=1).to_list()
    last_line = last_line[gold+silver]
    print(last_line)

              bng      vox
escaño_8  58135.0  50325.0
             psoe       pp
escaño_4  34924.0  29417.0
               vox  podemos_iu
escaño_12  55798.0     54266.0
               pp     psoe
escaño_6  39036.0  29765.0
          eh_bildu       pp
escaño_4   27453.0  25506.0
             psoe  podemos_iu
escaño_7  62070.0     44650.0
              vox       pp
escaño_3  17313.0  16263.0
               pp     psoe
escaño_6  46371.0  35578.0
              psoe  erc_sobiranistes
escaño_32  79789.0           77363.0
               pp  eaj_pnv
escaño_8  55621.0  55494.0
               pp      vox
escaño_4  30614.0  29579.0
              vox       pp
escaño_4  35807.0  30763.0
               cs     psoe
escaño_9  55490.0  47067.0
               pp     psoe
escaño_5  42291.0  38014.0
          podemos_iu       pp
escaño_5     39251.0  35088.0
              vox     psoe
escaño_1  11752.0  10455.0
               pp     psoe
escaño_5  37417.0  30682.0
               pp     psoe
escaño_6  49999.0  48920.0
             psoe      vox
escaño_3  20335.0  20108.0
          eh_bildu  eaj_pnv
escaño_6   49475.0  38920.0
          ecp_guanyem_el_canvi   cup_pr
escaño_6               33710.0  31703.0
               pp      vox
escaño_7  52596.0  49964.0
               pp     psoe
escaño_3  30443.0  20583.0
             psoe  podemos_iu
escaño_5  30552.0     30389.0
             psoe      vox
escaño_3  19050.0  17237.0
              vox     psoe
escaño_8  38760.0  38522.0
             psoe       pp
escaño_5  47245.0  41027.0
               pp     psoe
escaño_4  28225.0  19161.0
             psoe  podemos_iu
escaño_8  47026.0     37324.0
              vox       pp
escaño_4  40884.0  37336.0
             psoe  jxcat_junts
escaño_4  29983.0      23386.0
             psoe       pp
escaño_4  28768.0  22843.0
                pp     psoe
escaño_37  88747.0  87036.0
                pp      vox
escaño_11  54392.0  54093.0
              pp     cpm
escaño_1  9136.0  8955.0
              psoe       cs
escaño_10  59051.0  53201.0
              na+     psoe
escaño_5  49539.0  41867.0
             psoe       pp
escaño_4  28467.0  22526.0
               pp     psoe
escaño_3  17097.0  15923.0
               pp     psoe
escaño_7  50653.0  41594.0
               pp     psoe
escaño_4  33857.0  28740.0
               pp     psoe
escaño_7  46717.0  44172.0
              vox       pp
escaño_3  14569.0  14028.0
              psoe      vox
escaño_12  76077.0  62937.0
               pp    psoe
escaño_2  15247.0  8021.0
             psoe  erc_sobiranistes
escaño_6  36820.0           32927.0
               pp  teruel_existe!
escaño_3  17520.0          9880.0
              vox     psoe
escaño_6  43024.0  38760.0
                pp     psoe
escaño_15  76732.0  75175.0
               pp  podemos_iu
escaño_5  45928.0     34313.0
              vox       pp
escaño_3  17036.0  16747.0
             psoe       cs
escaño_7  52775.0  47001.0

In [221]:
last_line

,psoe,pp,vox,podemos_iu,cs,m_pais_cha_equo
escaño_7,52775.333333,39969.666667,46176.5,28937.5,47001.0,23196.0

['psoe']

In [190]:
prov_dict

{'15': {'tabla':                      pp           psoe  podemos_eu      bng      vox       cs
  votos     187127.000000  184178.000000     77069.0  58135.0  50325.0  28469.0
  escaño_1  187127.000000  184178.000000     77069.0  58135.0  50325.0  28469.0
  escaño_2   93563.500000  184178.000000     77069.0  58135.0  50325.0  28469.0
  escaño_3   93563.500000   92089.000000     77069.0  58135.0  50325.0  28469.0
  escaño_4   62375.666667   92089.000000     77069.0  58135.0  50325.0  28469.0
  escaño_5   62375.666667   61392.666667     77069.0  58135.0  50325.0  28469.0
  escaño_6   62375.666667   61392.666667     38534.5  58135.0  50325.0  28469.0
  escaño_7   46781.750000   61392.666667     38534.5  58135.0  50325.0  28469.0
  escaño_8   46781.750000   46044.500000     38534.5  58135.0  50325.0  28469.0,
  'escaños':             acumulado
  pp                  3
  psoe                3
  podemos_eu          1
  bng                 1
  vox                 0
  cs                  0},
 '2': {'tabla':              psoe       pp      vox  podemos_iu       cs
  votos     69848.0  58835.0  44306.0     20771.0  15947.0
  escaño_1  69848.0  58835.0  44306.0     20771.0  15947.0
  escaño_2  34924.0  58835.0  44306.0     20771.0  15947.0
  escaño_3  34924.0  29417.5  44306.0     20771.0  15947.0
  escaño_4  34924.0  29417.5  22153.0     20771.0  15947.0,
  'escaños':             acumulado
  psoe                2
  pp                  1
  vox                 1
  podemos_iu          0
  cs                  0},
 '3': {'tabla':                     psoe             pp            vox  podemos_iu       cs  \
  votos      240202.000000  207310.000000  167395.000000    108533.0  69143.0
  escaño_1   240202.000000  207310.000000  167395.000000    108533.0  69143.0
  escaño_2   120101.000000  207310.000000  167395.000000    108533.0  69143.0
  escaño_3   120101.000000  103655.000000  167395.000000    108533.0  69143.0
  escaño_4   120101.000000  103655.000000   83697.500000    108533.0  69143.0
  escaño_5    80067.333333  103655.000000   83697.500000    108533.0  69143.0
  escaño_6    80067.333333  103655.000000   83697.500000     54266.5  69143.0
  escaño_7    80067.333333   69103.333333   83697.500000     54266.5  69143.0
  escaño_8    80067.333333   69103.333333   55798.333333     54266.5  69143.0
  escaño_9    60050.500000   69103.333333   55798.333333     54266.5  69143.0
  escaño_10   60050.500000   69103.333333   55798.333333     54266.5  34571.5
  escaño_11   60050.500000   51827.500000   55798.333333     54266.5  34571.5
  escaño_12   48040.400000   51827.500000   55798.333333     54266.5  34571.5

             mes_compromis
  votos            35612.0
  escaño_1         35612.0
  escaño_2         35612.0
  escaño_3         35612.0
  escaño_4         35612.0
  escaño_5         35612.0
  escaño_6         35612.0
  escaño_7         35612.0
  escaño_8         35612.0
  escaño_9         35612.0
  escaño_10        35612.0
  escaño_11        35612.0
  escaño_12        35612.0  ,
  'escaños':                acumulado
  psoe                   4
  pp                     3
  vox                    3
  podemos_iu             1
  cs                     1
  mes_compromis          0},
 '4': {'tabla':              psoe           vox       pp  podemos_iu       cs
  votos     89295.0  80714.000000  78072.0     24400.0  22835.0
  escaño_1  89295.0  80714.000000  78072.0     24400.0  22835.0
  escaño_2  44647.5  80714.000000  78072.0     24400.0  22835.0
  escaño_3  44647.5  40357.000000  78072.0     24400.0  22835.0
  escaño_4  44647.5  40357.000000  39036.0     24400.0  22835.0
  escaño_5  29765.0  40357.000000  39036.0     24400.0  22835.0
  escaño_6  29765.0  26904.666667  39036.0     24400.0  22835.0,
  'escaños':             acumulado
  psoe                2
  vox                 2
  pp                  2
  podemos_iu          0
  cs                  0},
 '1': {'tabla':           eaj_pnv     psoe  podemos_iu  eh_bildu       pp     vox
  votos     40262.0  37488.0     28186.0   27453.0  25506.0  6421.0
  escaño_1  40262.0  37488.0     28186.0   27453.0  25506.0  6421.0
  escaño_2  20131.0  37488.0     28186.0   27453.0  25506.0  6421.0
  escaño_3  20131.0  18744.0     28186.0   27453.0  25506.0  6421.0
  escaño_4  20131.0  18744.0     14093.0   27453.0  25506.0  6421.0,
  'escaños':             acumulado
  eaj_pnv             1
  psoe                1
  podemos_iu          1
  eh_bildu            1
  pp                  0
  vox                 0},
 '33': {'tabla':                    psoe        pp  podemos_iu      vox       cs
  votos     186211.000000  129945.0     89301.0  88788.0  37374.0
  escaño_1  186211.000000  129945.0     89301.0  88788.0  37374.0
  escaño_2   93105.500000  129945.0     89301.0  88788.0  37374.0
  escaño_3   93105.500000   64972.5     89301.0  88788.0  37374.0
  escaño_4   62070.333333   64972.5     89301.0  88788.0  37374.0
  escaño_5   62070.333333   64972.5     44650.5  88788.0  37374.0
  escaño_6   62070.333333   64972.5     44650.5  44394.0  37374.0
  escaño_7   62070.333333   43315.0     44650.5  44394.0  37374.0,
  'escaños':             acumulado
  psoe                3
  pp                  2
  podemos_iu          1
  vox                 1
  cs                  0},
 '5': {'tabla':                pp     psoe      vox      cs  podemos_iu     xav
  votos     32527.0  24474.0  17313.0  6119.0      6059.0  5416.0
  escaño_1  32527.0  24474.0  17313.0  6119.0      6059.0  5416.0
  escaño_2  16263.5  24474.0  17313.0  6119.0      6059.0  5416.0
  escaño_3  16263.5  12237.0  17313.0  6119.0      6059.0  5416.0,
  'escaños':             acumulado
  pp                  1
  psoe                1
  vox                 1
  cs                  0
  podemos_iu          0
  xav                 0},
 '6': {'tabla':                    psoe       pp      vox  podemos_iu       cs
  votos     142312.000000  92742.0  64016.0     33971.0  29520.0
  escaño_1  142312.000000  92742.0  64016.0     33971.0  29520.0
  escaño_2   71156.000000  92742.0  64016.0     33971.0  29520.0
  escaño_3   71156.000000  46371.0  64016.0     33971.0  29520.0
  escaño_4   47437.333333  46371.0  64016.0     33971.0  29520.0
  escaño_5   47437.333333  46371.0  32008.0     33971.0  29520.0
  escaño_6   35578.000000  46371.0  32008.0     33971.0  29520.0,
  'escaños':             acumulado
  psoe                3
  pp                  2
  vox                 1
  podemos_iu          0
  cs                  0},
 '8': {'tabla':                     psoe  erc_sobiranistes  ecp_guanyem_el_canvi  \
  votos      638319.000000     618909.000000         452482.000000
  escaño_1   638319.000000     618909.000000         452482.000000
  escaño_2   319159.500000     618909.000000         452482.000000
  escaño_3   319159.500000     309454.500000         452482.000000
  escaño_4   319159.500000     309454.500000         226241.000000
  escaño_5   319159.500000     309454.500000         226241.000000
  escaño_6   212773.000000     309454.500000         226241.000000
  escaño_7   212773.000000     206303.000000         226241.000000
  escaño_8   212773.000000     206303.000000         150827.333333
  escaño_9   212773.000000     206303.000000         150827.333333
  escaño_10  159579.750000     206303.000000         150827.333333
  escaño_11  159579.750000     154727.250000         150827.333333
  escaño_12  159579.750000     154727.250000         150827.333333
  escaño_13  159579.750000     154727.250000         150827.333333
  escaño_14  159579.750000     154727.250000         150827.333333
  escaño_15  159579.750000     154727.250000         150827.333333
  escaño_16  127663.800000     154727.250000         150827.333333
  escaño_17  127663.800000     123781.800000         150827.333333
  escaño_18  127663.800000     123781.800000         113120.500000
  escaño_19  106386.500000     123781.800000         113120.500000
  escaño_20  106386.500000     103151.500000         113120.500000
  escaño_21  106386.500000     103151.500000         113120.500000
  escaño_22  106386.500000     103151.500000          90496.400000
  escaño_23  106386.500000     103151.500000          90496.400000
  escaño_24   91188.428571     103151.500000          90496.400000
  escaño_25   91188.428571      88415.571429          90496.400000
  escaño_26   91188.428571      88415.571429          90496.400000
  escaño_27   79789.875000      88415.571429          90496.400000
  escaño_28   79789.875000      88415.571429          75413.666667
  escaño_29   79789.875000      88415.571429          75413.666667
  escaño_30   79789.875000      77363.625000          75413.666667
  escaño_31   79789.875000      77363.625000          75413.666667
  escaño_32   79789.875000      77363.625000          75413.666667

               jxcat_junts        pp            vox         cup_pr  \
  votos      343931.000000  225645.0  184715.000000  179041.000000
  escaño_1   343931.000000  225645.0  184715.000000  179041.000000
  escaño_2   343931.000000  225645.0  184715.000000  179041.000000
  escaño_3   343931.000000  225645.0  184715.000000  179041.000000
  escaño_4   343931.000000  225645.0  184715.000000  179041.000000
  escaño_5   171965.500000  225645.0  184715.000000  179041.000000
  escaño_6   171965.500000  225645.0  184715.000000  179041.000000
  escaño_7   171965.500000  225645.0  184715.000000  179041.000000
  escaño_8   171965.500000  225645.0  184715.000000  179041.000000
  escaño_9   171965.500000  112822.5  184715.000000  179041.000000
  escaño_10  171965.500000  112822.5  184715.000000  179041.000000
  escaño_11  171965.500000  112822.5  184715.000000  179041.000000
  escaño_12  171965.500000  112822.5   92357.500000  179041.000000
  escaño_13  171965.500000  112822.5   92357.500000   89520.500000
  escaño_14  171965.500000  112822.5   92357.500000   89520.500000
  escaño_15  114643.666667  112822.5   92357.500000   89520.500000
  escaño_16  114643.666667  112822.5   92357.500000   89520.500000
  escaño_17  114643.666667  112822.5   92357.500000   89520.500000
  escaño_18  114643.666667  112822.5   92357.500000   89520.500000
  escaño_19  114643.666667  112822.5   92357.500000   89520.500000
  escaño_20  114643.666667  112822.5   92357.500000   89520.500000
  escaño_21   85982.750000  112822.5   92357.500000   89520.500000
  escaño_22   85982.750000  112822.5   92357.500000   89520.500000
  escaño_23   85982.750000   75215.0   92357.500000   89520.500000
  escaño_24   85982.750000   75215.0   92357.500000   89520.500000
  escaño_25   85982.750000   75215.0   92357.500000   89520.500000
  escaño_26   85982.750000   75215.0   61571.666667   89520.500000
  escaño_27   85982.750000   75215.0   61571.666667   89520.500000
  escaño_28   85982.750000   75215.0   61571.666667   89520.500000
  escaño_29   85982.750000   75215.0   61571.666667   59680.333333
  escaño_30   85982.750000   75215.0   61571.666667   59680.333333
  escaño_31   85982.750000   75215.0   61571.666667   59680.333333
  escaño_32   68786.200000   75215.0   61571.666667   59680.333333

                        cs
  votos      174124.000000
  escaño_1   174124.000000
  escaño_2   174124.000000
  escaño_3   174124.000000
  escaño_4   174124.000000
  escaño_5   174124.000000
  escaño_6   174124.000000
  escaño_7   174124.000000
  escaño_8   174124.000000
  escaño_9   174124.000000
  escaño_10  174124.000000
  escaño_11  174124.000000
  escaño_12  174124.000000
  escaño_13  174124.000000
  escaño_14   87062.000000
  escaño_15   87062.000000
  escaño_16   87062.000000
  escaño_17   87062.000000
  escaño_18   87062.000000
  escaño_19   87062.000000
  escaño_20   87062.000000
  escaño_21   87062.000000
  escaño_22   87062.000000
  escaño_23   87062.000000
  escaño_24   87062.000000
  escaño_25   87062.000000
  escaño_26   87062.000000
  escaño_27   87062.000000
  escaño_28   87062.000000
  escaño_29   87062.000000
  escaño_30   87062.000000
  escaño_31   58041.333333
  escaño_32   58041.333333  ,
  'escaños':                       acumulado
  psoe                          8
  erc_sobiranistes              7
  ecp_guanyem_el_canvi          5
  jxcat_junts                   4
  pp                            2
  vox                           2
  cup_pr                        2
  cs                            2},
 '48': {'tabla':             eaj_pnv           psoe  podemos_iu  eh_bildu       pp
  votos     221979.00  120566.000000     97125.0   94669.0  55621.0
  escaño_1  221979.00  120566.000000     97125.0   94669.0  55621.0
  escaño_2  110989.50  120566.000000     97125.0   94669.0  55621.0
  escaño_3  110989.50   60283.000000     97125.0   94669.0  55621.0
  escaño_4   73993.00   60283.000000     97125.0   94669.0  55621.0
  escaño_5   73993.00   60283.000000     48562.5   94669.0  55621.0
  escaño_6   73993.00   60283.000000     48562.5   47334.5  55621.0
  escaño_7   55494.75   60283.000000     48562.5   47334.5  55621.0
  escaño_8   55494.75   40188.666667     48562.5   47334.5  55621.0,
  'escaños':             acumulado
  eaj_pnv             3
  psoe                2
  podemos_iu          1
  eh_bildu            1
  pp                  1},
 '9': {'tabla':              psoe       pp      vox  podemos_iu       cs
  votos     64182.0  61228.0  29579.0     22058.0  16214.0
  escaño_1  64182.0  61228.0  29579.0     22058.0  16214.0
  escaño_2  32091.0  61228.0  29579.0     22058.0  16214.0
  escaño_3  32091.0  30614.0  29579.0     22058.0  16214.0
  escaño_4  21394.0  30614.0  29579.0     22058.0  16214.0,
  'escaños':             acumulado
  psoe                2
  pp                  2
  vox                 0
  podemos_iu          0
  cs                  0},
 '10': {'tabla':                   psoe       pp      vox  podemos_iu       cs
  votos     85135.000000  61527.0  35807.0     20101.0  15533.0
  escaño_1  85135.000000  61527.0  35807.0     20101.0  15533.0
  escaño_2  42567.500000  61527.0  35807.0     20101.0  15533.0
  escaño_3  42567.500000  30763.5  35807.0     20101.0  15533.0
  escaño_4  28378.333333  30763.5  35807.0     20101.0  15533.0,
  'escaños':             acumulado
  psoe                2
  pp                  1
  vox                 1
  podemos_iu          0
  cs                  0},
 '11': {'tabla':                psoe       vox             pp  podemos_iu       cs
  votos     188271.00  131205.0  111089.000000     93541.0  55490.0
  escaño_1  188271.00  131205.0  111089.000000     93541.0  55490.0
  escaño_2   94135.50  131205.0  111089.000000     93541.0  55490.0
  escaño_3   94135.50   65602.5  111089.000000     93541.0  55490.0
  escaño_4   94135.50   65602.5   55544.500000     93541.0  55490.0
  escaño_5   62757.00   65602.5   55544.500000     93541.0  55490.0
  escaño_6   62757.00   65602.5   55544.500000     46770.5  55490.0
  escaño_7   62757.00   43735.0   55544.500000     46770.5  55490.0
  escaño_8   47067.75   43735.0   55544.500000     46770.5  55490.0
  escaño_9   47067.75   43735.0   37029.666667     46770.5  55490.0,
  'escaños':             acumulado
  psoe                3
  vox                 2
  pp                  2
  podemos_iu          1
  cs                  1},
 '39': {'tabla':                pp     psoe      prc      vox  podemos_iu       cs
  votos     84583.0  76028.0  68830.0  48827.0     28376.0  15609.0
  escaño_1  84583.0  76028.0  68830.0  48827.0     28376.0  15609.0
  escaño_2  42291.5  76028.0  68830.0  48827.0     28376.0  15609.0
  escaño_3  42291.5  38014.0  68830.0  48827.0     28376.0  15609.0
  escaño_4  42291.5  38014.0  34415.0  48827.0     28376.0  15609.0
  escaño_5  42291.5  38014.0  34415.0  24413.5     28376.0  15609.0,
  'escaños':             acumulado
  pp                  2
  psoe                1
  prc                 1
  vox                 1
  podemos_iu          0
  cs                  0},
 '12': {'tabla':              psoe       pp      vox  podemos_iu       cs  mes_compromis
  votos     84078.0  70176.0  54849.0     39251.0  20302.0        18140.0
  escaño_1  84078.0  70176.0  54849.0     39251.0  20302.0        18140.0
  escaño_2  42039.0  70176.0  54849.0     39251.0  20302.0        18140.0
  escaño_3  42039.0  35088.0  54849.0     39251.0  20302.0        18140.0
  escaño_4  42039.0  35088.0  27424.5     39251.0  20302.0        18140.0
  escaño_5  28026.0  35088.0  27424.5     39251.0  20302.0        18140.0,
  'escaños':                acumulado
  psoe                   2
  pp                     1
  vox                    1
  podemos_iu             1
  cs                     0
  mes_compromis          0},
 '51': {'tabla':               vox     psoe      pp  podemos_iu      cs
  votos     11752.0  10455.0  7439.0      1300.0  1138.0
  escaño_1  11752.0  10455.0  7439.0      1300.0  1138.0,
  'escaños':             acumulado
  vox                 1
  psoe                0
  pp                  0
  podemos_iu          0
  cs                  0},
 '13': {'tabla':              psoe       pp      vox  podemos_iu       cs
  votos     92046.0  74835.0  56050.0     22250.0  18337.0
  escaño_1  92046.0  74835.0  56050.0     22250.0  18337.0
  escaño_2  46023.0  74835.0  56050.0     22250.0  18337.0
  escaño_3  46023.0  37417.5  56050.0     22250.0  18337.0
  escaño_4  46023.0  37417.5  28025.0     22250.0  18337.0
  escaño_5  30682.0  37417.5  28025.0     22250.0  18337.0,
  'escaños':             acumulado
  psoe                2
  pp                  2
  vox                 1
  podemos_iu          0
  cs                  0},
 '14': {'tabla':                    psoe       pp      vox  podemos_iu       cs
  votos     146761.000000  99999.0  82534.0     64769.0  36229.0
  escaño_1  146761.000000  99999.0  82534.0     64769.0  36229.0
  escaño_2   73380.500000  99999.0  82534.0     64769.0  36229.0
  escaño_3   73380.500000  49999.5  82534.0     64769.0  36229.0
  escaño_4   73380.500000  49999.5  41267.0     64769.0  36229.0
  escaño_5   48920.333333  49999.5  41267.0     64769.0  36229.0
  escaño_6   48920.333333  49999.5  41267.0     32384.5  36229.0,
  'escaños':             acumulado
  psoe                2
  pp                  2
  vox                 1
  podemos_iu          1
  cs                  0},
 '16': {'tabla':              psoe       pp      vox  podemos_iu      cs
  votos     40670.0  33721.0  20108.0      7529.0  5094.0
  escaño_1  40670.0  33721.0  20108.0      7529.0  5094.0
  escaño_2  20335.0  33721.0  20108.0      7529.0  5094.0
  escaño_3  20335.0  16860.5  20108.0      7529.0  5094.0,
  'escaños':             acumulado
  psoe                2
  pp                  1
  vox                 0
  podemos_iu          0
  cs                  0},
 '20': {'tabla':                 eaj_pnv  eh_bildu     psoe  podemos_iu       pp
  votos     116761.000000   98951.0  69342.0     57363.0  23619.0
  escaño_1  116761.000000   98951.0  69342.0     57363.0  23619.0
  escaño_2   58380.500000   98951.0  69342.0     57363.0  23619.0
  escaño_3   58380.500000   49475.5  69342.0     57363.0  23619.0
  escaño_4   58380.500000   49475.5  34671.0     57363.0  23619.0
  escaño_5   38920.333333   49475.5  34671.0     57363.0  23619.0
  escaño_6   38920.333333   49475.5  34671.0     28681.5  23619.0,
  'escaños':             acumulado
  eaj_pnv             2
  eh_bildu            2
  psoe                1
  podemos_iu          1
  pp                  0},
 '17': {'tabla':           erc_sobiranistes   jxcat_junts     psoe  ecp_guanyem_el_canvi  \
  votos              91932.0  88060.000000  52723.0               33710.0
  escaño_1           91932.0  88060.000000  52723.0               33710.0
  escaño_2           45966.0  88060.000000  52723.0               33710.0
  escaño_3           45966.0  44030.000000  52723.0               33710.0
  escaño_4           45966.0  44030.000000  26361.5               33710.0
  escaño_5           30644.0  44030.000000  26361.5               33710.0
  escaño_6           30644.0  29353.333333  26361.5               33710.0


In [116]:
"""parties_T = df_provincia[party_columns_prov].T
total_votos = int(parties_T.sum())
parties_T = parties_T[parties_T[parties_T.columns[0]] > 0.03*total_votos]
parties_T = parties_T.sort_values(by = parties_T.columns[0], ascending=False) 
parties_T = parties_T.rename(columns={parties_T.columns[0]:"votos"})
parties_T"""

'parties_T = df_provincia[party_columns_prov].T\ntotal_votos = int(parties_T.sum())\nparties_T = parties_T[parties_T[parties_T.columns[0]] > 0.03*total_votos]\nparties_T = parties_T.sort_values(by = parties_T.columns[0], ascending=False) \nparties_T = parties_T.rename(columns={parties_T.columns[0]:"votos"})\nparties_T'

In [117]:
"""current_votes = parties_T.copy()
current_votes["acumulado"] = 1
current_votes = current_votes.drop(columns =["votos"])
current_votes"""

'current_votes = parties_T.copy()\ncurrent_votes["acumulado"] = 1\ncurrent_votes = current_votes.drop(columns =["votos"])\ncurrent_votes'

In [118]:
"""
for idx in range(1,38):
    parties_T[f'escaño_{idx}'] = parties_T["votos"] / current_votes["acumulado"]
    max_col = parties_T[f'escaño_{idx}'].idxmax()
    print(f"escaño {idx}: ", max_col)
    current_votes.loc[current_votes.index == max_col,"acumulado"] += 1 
current_votes["acumulado"] = current_votes["acumulado"] -1"""

'\nfor idx in range(1,38):\n    parties_T[f\'escaño_{idx}\'] = parties_T["votos"] / current_votes["acumulado"]\n    max_col = parties_T[f\'escaño_{idx}\'].idxmax()\n    print(f"escaño {idx}: ", max_col)\n    current_votes.loc[current_votes.index == max_col,"acumulado"] += 1 \ncurrent_votes["acumulado"] = current_votes["acumulado"] -1'

In [34]:
"""# nseats, minper, census, white, sploitv, nabs, dcandi
nseats = 37
minper = 3.0
dcandi = df_provincia[party_columns_prov].to_dict('records')[0]
# Performs the dhont calc
result = dhondt(nseats, minper, dcandi)
# Returns data calc
print('<seats: {0}>'.format(sorted(result.repre.items(), key=lambda p: p[1], reverse=True)))"""

"# nseats, minper, census, white, sploitv, nabs, dcandi\nnseats = 37\nminper = 3.0\ndcandi = df_provincia[party_columns_prov].to_dict('records')[0]\n# Performs the dhont calc\nresult = dhondt(nseats, minper, dcandi)\n# Returns data calc\nprint('<seats: {0}>'.format(sorted(result.repre.items(), key=lambda p: p[1], reverse=True)))"

## Filtrar por Madrid

In [ ]:
df_comunidad = df[df["codigo_de_provincia"] == CODIGO_COMUNIDAD]  # 28 = Madrid

In [ ]:
df_comunidad.shape

In [18]:
df_comunidad.columns

NameError: name 'df_comunidad' is not defined

# Mapa Comunidad por munipios

In [ ]:
#map_path = "../../data/raw/mapa_municipios/Municipios_IGN-shp/Municipios_IGN.shp"
#geodf = gpd.read_file(map_path)
#geodf["COMUNIDAD"] = geodf["CODIGOINE"].apply(lambda x: str(x)[:2])
#geodf = geodf[geodf["COMUNIDAD"] == str(CODIGO_COMUNIDAD).zfill(2)]
#geodf_reduced = geodf[["CODIGOINE","geometry"]]
#geojson_save_path = "../../data/raw/mapa_municipios/Municipios_IGN-shp/madrid_municipios.geojson"
#guardar
#geodf_reduced.to_file(geojson_save_path, driver = "GeoJSON")

In [ ]:
#cargar
with open(GEOJSON_PATH) as geofile:
    geojson = json.load(geofile)

# Mapa de ganadores

In [ ]:
# creando una columna con el partido con más votos
df_comunidad["ganador"] = df_comunidad[party_columns].idxmax(axis=1)
df_comunidad["ganador"] = df_comunidad.apply(lambda x: None if x[party_columns].sum() == 0 else x["ganador"], axis=1)
df_comunidad = df_comunidad[df_comunidad["ganador"].notnull()]

In [ ]:
df_comunidad["ganador"].unique()

# Resultados electorales

In [ ]:
color_map = {'ucd':"#FFA07A",
             'psoe':"#E52B50", 
             'pp':"#1E90FF", 
             'ap':"#FFFF00",              
             'pce':"#FF0000",              
             'uce':"#FF0000",              
             'ap_pdp':"#FFFF00",              
             'pcoe':"#FF0000",              
             'pst':"#FF0000",              
             'ap_pdp_pl':"#FFFF00",              
             'cds':"#66CDAA",              
             'iu':"#32CD32",
             'fe':"#000000", 
             'ciudadanos':"#FFA500",
             'podemos_iu':"#9370DB",    
             'podemos_iu_equo':"#9370DB",                 
             'podemos':"#9370DB",
             'vox':"#00FF00"}

In [ ]:
# filtros
#df_com_elecciones = df_comunidad[df_comunidad["yearmonth"] == ELECCIONES]
df_com_elecciones = df_comunidad.copy()
df_com_elecciones = df_com_elecciones[["ganador", "nombre_de_municipio", "CODIGOINE", "year", "month"]].sort_values(["year", "month"], ascending=True)

In [ ]:
df_com_elecciones.shape

In [ ]:
df_com_elecciones.tail()

# Gráficos

In [ ]:
# El gráfico está mal !!!
"""## GRAFICO --------------------
#Forzar ganadores en el primer frame para que funcione
df_forze_winner = pd.DataFrame({"ganador":df_com_elecciones.ganador.unique(), 
              "nombre_de_municipio":["UNKNOWN"] * len(df_com_elecciones.ganador.unique()),
              "CODIGOINE":["UNKNOWN"] * len(df_com_elecciones.ganador.unique()),
              "year":[1977] * len(df_com_elecciones.ganador.unique()),
              "month":[6] * len(df_com_elecciones.ganador.unique())}) 
df_tmp = df_com_elecciones.append(df_forze_winner, ignore_index = True)
fig_map_animate = px.choropleth_mapbox(data_frame=df_tmp, geojson=geojson, locations='CODIGOINE', 
                           featureidkey="properties.CODIGOINE", color='ganador', mapbox_style="carto-positron", 
                           hover_data=["nombre_de_municipio", "ganador", "year", "month"],  
                           color_discrete_map=color_map, zoom=7,
                           center={"lat": 40.463667, "lon": -3.74922}, animation_frame="year",
                           animation_group="ganador",height=650,
                           title= f"Ganador por municipio de las Elecciones Generales en la Comunidad de Madrid")
fig_map_animate.show()"""

197706
197903
198210
198606
198910
199306
199603
200003
200403
200803
201111
201512
201606
201904
201911

In [ ]:
## GRAFICO --------------------
# una única elección
ELECCIONES = 201911
df_tmp = df_com_elecciones.copy()
df_tmp["yearmonth"] = df_tmp["year"].astype(str).str.zfill(4) + df_tmp["month"].astype(str).str.zfill(2)
df_tmp = df_tmp[df_tmp["yearmonth"] == str(ELECCIONES)]
fig_map_frozen = px.choropleth_mapbox(data_frame=df_tmp, 
                           geojson=geojson, locations='CODIGOINE', 
                           featureidkey="properties.CODIGOINE", color='ganador', mapbox_style="carto-positron", 
                           hover_data=["nombre_de_municipio", "ganador"], zoom=8, color_discrete_map=color_map,
                           center={"lat": 40.53, "lon": -3.75}, height=800,
                           title= f"Elecciones Generales {str(ELECCIONES)[:4]}-{str(ELECCIONES)[-2:]} en Madrid")
fig_map_frozen.show()
#pio.write_html(fig_map_frozen, file=f"../../../../Downloads/elecciones_madrid_{ELECCIONES}.html", auto_open=False)

# Evolución votos

In [ ]:
# evolucion partidos mas votados, lineas dejar rastro, filtro por municipio
CODIGOINE_MUNICIPIO="28092"

In [ ]:
df_municipio = df_comunidad[df_comunidad.CODIGOINE == CODIGOINE_MUNICIPIO]
nombre_municipio = df_municipio.nombre_de_municipio.unique()[0]
df_municipio.head()

In [ ]:
party_bool = (df_municipio[party_columns].sum() == 0)
drop_parties = list(party_bool[party_bool].index)
df_municipio_filtered = df_municipio.drop(columns=drop_parties)
df_party_series = df_municipio_filtered.melt(id_vars=['year', "month"], 
                                             value_vars=[x for x in party_columns if x not in drop_parties])
df_party_series = df_party_series.rename(columns={"variable":"partido", "value":"votos"})
df_party_series = df_party_series[~((df_party_series.year == 2019) & (df_party_series.month == 4))]

top_parties = list(df_party_series.groupby("partido")
                     .sum("votos").sort_values("votos", ascending=False)[:15]
                     .reset_index()["partido"].unique())
df_party_series = df_party_series[df_party_series["partido"].isin(top_parties)]
df_party_series = df_party_series.sort_values(["year", "month", "partido"], ascending=True)
df_party_series["partido"] = df_party_series["partido"].replace({'ap_pdp_pl': "ap", 'ap_pdp': "ap",
                                                            "podemos_iu":"podemos", "podemos_iu_equo":"podemos",
                                                            "iu_lv":"iu"})
df_party_series = df_party_series.groupby(["year","month","partido"]).sum().reset_index()
df_party_series["size"] = 5

In [ ]:
## GRAFICO --------------------
max_y = int(df_party_series["votos"].max()*1.1)
fig_town_time = px.scatter(df_party_series, x="year", y="votos", animation_frame="year",animation_group="partido",
                 size="size", height=600,template="plotly_white",
                 color="partido", range_x=[1976,2020], range_y=[0,max_y], color_discrete_map=color_map,
                 title= f"Elecciones Generales a lo largo del tiempo en {nombre_municipio}")
fig_town_time.show()

In [ ]:
py.plot(fig_town_time, filename = 'elecciones_generales_mostoles_tiempo', auto_open=True)

In [ ]:
## GRAFICO --------------------
fig_town_lines = px.line(df_party_series, x="year", y="votos", color="partido", line_group="partido", hover_name="partido",
        line_shape="linear", render_mode="svg", color_discrete_map=color_map,range_x=[1976,2020],template="plotly_white",
        title= f"Elecciones Generales a lo largo del tiempo en {nombre_municipio}")
fig_town_lines.show()